- name: Install PostgreSQL
  apt:
    name: "{{ postgresql_version }}"
    state: present
    update_cache: yes

- name: Create data directory for PostgreSQL
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory

- name: Start PostgreSQL service
  service:
    name: postgresql
    enabled: yes
    state: started
